language: python
dist: xenial
notifications:
  slack:
    secure: kBtuSHJcPUxo1Fcl5TQ+iDekLMCPbEQ90gS3tR70CqZyH5kMyRBsjpVnkHYaNSXer3pUE+ThQm4iBYKdT+APEEOkcB0zCSChQ6XRQ4GTvRWKi8DPh8G8iJ+nZu8UAnTmBa+ewNzq+/kVcnd8qjJ379Cr34TgG5ne+5FCiFhLgnnuJY/yI1PUj5Ymj5tJl7OaKQeARQxhcTuotL7ZLPdK/s6Rf4wsKddblUtxnD4t1hJpS/6JEY1JvQ/rAAFDNvLT8JcawsSDJnolrfFWZD9omLFWktNgEYHx508XFO49Sag9QMl9GKvl7tXMyK4mf32tSntC0izpjVRN8bRMRId9Avp72O5Bu9q+EsuJ4syrfcK1qgnSU3UqU6Ci/3yztpElLfrx3EB84Nwh5XV4rF66zxBUPHsMFYGeEMGdoe4eFid8P3/1PgF02Pg4Jst3cgot6oqwhJCEUNcgP0U+X7uMuVomN9eEsTOMpoeq7R0aubAJVgE/5WqLUNPMvF4C9FHHbBxzFUtuBEFTuWxjYJszKBnmH40UiiZvWF5sIIScQaRD9SbjdnaSTkQ8SrGAKJnEJ4O1+ql62JWU/kceAilVW0toiA0LDwBvjw8Kv6jHfNRUZNtiIxMnokuXa/mgKRxRIlhXUAOr+HuJqxaKOvxJ6CfG0bm0gNSWzOO+0CjH3Yw=
  on_success: change
  on_failure: always
matrix:
  include:
  - python: 3.7
before_install:
- sudo apt-get update
- sudo apt-get install portaudio19-dev
install:
- pip install -r requirements.txt
script:
- pytest --cov=good_stuff --cov=test
- flake8 . --exit-zero
after_success:
- coveralls
